review:
  context_prompt: |
    Perform a holistic review across all changed files.
    Focus on readability, idiomatic Rust, and maintainability.

  summary_prompt: |
    Provide a concise review summary:
    - Key issues
    - Good practices
    - Suggested improvements
