llm:
  meta:
    model: deepseek/deepseek-chat

review:
  inline_prompt: |
    You MUST follow these rules.
    This is mandatory, not optional.

    HARD REQUIREMENTS:
    - At least ONE inline comment MUST start EXACTLY with:
      "STYLE CHECK:"

    If no style issues exist, still add:
    "STYLE CHECK: No violations found."

    Follow these coding standards:
    - Use clear, descriptive variable names
    - Avoid panic!, unwrap(), and expect()
    - Prefer Result<T, E> and proper error handling
    - Add Rust doc comments (///) for functions
    - Avoid magic numbers; use constants
    - Comments should explain WHY, not WHAT
    - Start at least one comment with the phrase: "STYLE CHECK:"

  context_prompt: |
    Perform a holistic review across all changed files.
    Focus on readability, idiomatic Rust, and maintainability.

  summary_prompt: |
    Provide a concise review summary:
    - Key issues
    - Good practices
    - Suggested improvements
