review:
  inline_prompt: |
    Follow these coding standards also:
    - Use clear, descriptive variable names
    - Add Rust doc comments (///) for functions
    - Avoid magic numbers; use constants
    - Comments should explain WHY, not WHAT

  summary_prompt: |
    Provide a concise review summary:
    - Key issues
    - Good practices
    - Suggested improvements
